#ifndef UNTITLED1FGFGHFGHFHFHF_GLOBAL_H
#define UNTITLED1FGFGHFGHFHFHF_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(UNTITLED1FGFGHFGHFHFHF_LIBRARY)
#define UNTITLED1FGFGHFGHFHFHF_EXPORT Q_DECL_EXPORT
#else
#define UNTITLED1FGFGHFGHFHFHF_EXPORT Q_DECL_IMPORT
#endif

#endif // UNTITLED1FGFGHFGHFHFHF_GLOBAL_H
